version: '3.7'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - back/.back_env
    working_dir: /code
    depends_on:
      - db
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"   
    restart: on-failure
    networks:
      - nginx_network


  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p 5433
    expose:
      - "5433"
    ports:
      - '5433:5433'
    networks:
      - nginx_network




networks:
  nginx_network:
    driver: bridge

volumes:
  db:


