version: '3.7'

services:

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - back/.back_env
    working_dir: /code/back
    depends_on:
      - db
    volumes:
      - ./back:/code/back
    ports:
      - "8000:8000"   
    restart: on-failure
    networks:
      - full_stack_network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /code/front
    restart: on-failure
    environment:
      DEBUG: 1
    volumes:
      - ./front:/code
    ports:
      - 5000:5000
    depends_on:
      - db
      - back
    networks:
      - full_stack_network


  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p 5433
    expose:
      - "5433"
    ports:
      - '5433:5433'
    networks:
      - full_stack_network




networks:
  full_stack_network:
    driver: bridge

volumes:
  db:


